# Generated by Django 4.0.4 on 2022-04-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_work_day', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Dairie',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=70)),
                ('course_name', models.CharField(max_length=70)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Course Group',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.group')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('t', 'Teacher'), ('s', 'Supervisor')], default='t', max_length=1)),
            ],
            options={
                'verbose_name': 'Supervisor',
            },
        ),
        migrations.CreateModel(
            name='Work_Type_And_Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('work_done', models.TextField()),
                ('learning_type', models.CharField(choices=[('WR', 'Working remote'), ('OS', 'On the site'), ('HM', 'Hybrid model')], max_length=2)),
                ('diary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.diary')),
            ],
            options={
                'verbose_name': 'Dairy content & hour',
            },
        ),
        migrations.CreateModel(
            name='Work_Off_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isHoliday', models.BooleanField(default=False)),
                ('day', models.DateField()),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.group')),
            ],
            options={
                'verbose_name': 'Work days and Holiday',
            },
        ),
        migrations.CreateModel(
            name='Work_Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.group')),
            ],
            options={
                'verbose_name': 'Work Calendar',
            },
        ),
        migrations.CreateModel(
            name='Weekly_Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_week', models.PositiveIntegerField()),
                ('wasSupported', models.CharField(choices=[('0', 'Not at all'), ('1', 'Somewhat'), ('2', 'Appropriate amount')], max_length=1)),
                ('wasProvidedDevSupport', models.CharField(choices=[('0', 'Not at all'), ('1', 'Somewhat'), ('2', 'Appropriate amount')], max_length=1)),
                ('didLearn', models.CharField(choices=[('0', 'Not at all'), ('1', 'Somewhat'), ('2', 'Appropriate amount')], max_length=1)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('accepted_date_student', models.DateField(blank=True, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.student')),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dairy.supervisor')),
            ],
            options={
                'verbose_name': 'Student & Supervisor Acceptance',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dairy.supervisor'),
        ),
        migrations.AddField(
            model_name='diary',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy.student'),
        ),
    ]
