# Generated by Django 4.0.4 on 2022-04-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name': 'Diaries'},
        ),
        migrations.AlterModelOptions(
            name='work_type_and_period',
            options={'verbose_name': 'Diary content & hour'},
        ),
        migrations.RenameField(
            model_name='diary',
            old_name='date',
            new_name='diary_date',
        ),
        migrations.DeleteModel(
            name='Work_Calendar',
        ),
    ]
